Change LINKFLAGS to FRAMEWORKS which is supported since Scons 0.96.91
Tested on
System Version: macOS 10.15.3 (19D76)

SCons by Steven Knight et al.:
script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
engine path: ['/usr/local/Cellar/scons/3.1.2_1/libexec/scons-local/SCons']

Xcode 11.3.1
Build version 11C504

Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0

scons p=iphone
scons: Reading SConscript files ...
FileNotFoundError: [Errno 2] No such file or directory: '$IPHONEPATH/usr/bin/${ios_triple}clang++':
  File "/Users/psuedofinnish/git_repo/godot/SConstruct", line 359:
    vanilla = methods.is_vanilla_clang(env)
  File "/Users/psuedofinnish/git_repo/godot/methods.py", line 554:
    version = decode_utf8(subprocess.check_output([env['CXX'], '--version']).strip())
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489:
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854:
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702:
    raise child_exception_type(errno_num, err_msg, err_filename)

Issue #36720